// PROFILE
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_USER_PROFILE_IN_PROGRESS = 'SET_USER_PROFILE_IN_PROGRESS';
export const SET_USER_STATUS = 'SET_USER_STATUS';
export const ADD_POST = 'ADD_POST';
export const CHANGE_NEW_POST_VALUE = 'CHANGE_NEW_POST_VALUE';

// DIALOGS
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CHANGE_NEW_MESSAGE_VALUE = 'CHANGE_NEW_MESSAGE_VALUE';

// USERS
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const SET_USERS = 'SET_USERS';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const TOGGLE_USERS_IS_LOADING = 'TOGGLE_USERS_IS_LOADING';
export const TOGGLE_FOLLOWING_IN_PROGRESS = 'TOGGLE_FOLLOWING_IN_PROGRESS';

// AUTH
export const SET_AUTH_USER_DATA = 'SET_AUTH_USER_DATA';
export const SET_LOGIN_FORM_ERROR = 'SET_LOGIN_FORM_ERROR';

// APP
export const SET_INITIALIZED = 'SET_INITIALIZED';
